In [3]:
#import numpy as np
#def find_complete_list(pair_list,song_length):
#    """
#    Finds all smaller diagonals (and the associated pairs of repeats) 
#    that are contained in pair_list, which is composed of larger 
#    diagonals found in find_initial_repeats.
        
#    Args
#    ----
#    pair_list: np.array
#        list of pairs of repeats found in earlier step
#        (bandwidths MUST be in ascending order). If you have
#        run find_initial_repeats before this script,
#        then pair_list will be ordered correctly. 
           
#    song_length: int
#        song length, which is the number of audio shingles.
   
#    Returns
#    -------  
#    lst_out: np.array 
#        list of pairs of repeats with smaller repeats added
#    """

In [4]:
import numpy as np

In [193]:
#Inputs: 
pair_list = np.array([[1, 15, 31, 45, 15], 
                      [1, 10, 46, 55, 10], 
                      [31, 40, 46, 55, 10],
                      [10, 20, 40, 50, 15]])
song_length = 55

In [194]:
# Find the list of unique repeat lengths
bw_found = np.unique(pair_list[:,4])
print(bw_found)

[10 15]


In [195]:
bw_num = np.size(bw_found, axis=0)
print(bw_num)

2


In [196]:
longest_bw = bw_found[-1]
longest_bw

15

**CONCERNED: How is this finding the row with a bandwith = length of song?**

In [197]:
song_length = 15

In [198]:
# If the longest bandwidth is the length of the song, then remove that row or rows 
if song_length == longest_bw: 
    #Find row or rows that needs to be removed 
    row = np.where(pair_list[:,4] == longest_bw)
    
    #If there are multiple rows that have a bw of the length of the song
    if np.size(row, axis = 1) > 1:
        #Counter ensures indices will match up with the rows of the current pair_list being worked on 
        counter = 0
        for index in row[0]:
            #Finds the index of the row that needs to be removed 
            row_index = index - counter 
            #Removes row 
            pair_list = np.delete(pair_list, row_index, 0)
            #Increment counter since pair_list has been transformed 
            counter = counter + 1  
    else:
        pair_list = np.delete(pair_list, row[0], 0)
    
    #Remove longest bandwidth from list of repeat lengths 
    longest_unique_index = np.where(bw_found == longest_bw)
    bw_found = np.delete(bw_found, longest_unique_index, None)

    #Decrement number of unique repeat lengths
    bw_num = bw_num - np.size(longest_unique_index, axis = 0)

In [200]:
# Initalize temp variables
p = np.size(pair_list, axis = 0)
print(p)

2


In [202]:
add_mat = []
print(add_mat)

[]


% Step 1: For each found bandwidth, search upwards (i.e. search the larger 
%         bandwidths) and add all found diagonals to the variable ADD_MAT

for i = 1:b

    % Set the bandwidth based on BFOUND
    
    bw = bfound(i); 
    
    % Isolate pairs of repeats that are length BW
    
    bsnds = find(pair_lst(:,5) == bw, 1);
    bends = find(pair_lst(:,5) > bw, 1) - 1; % This is ok since [] - 1 = []
    if isempty(bends)
        bends = p;
    end
    
    % Part A1: Isolate all starting time steps of the repeats of length BW
    
    SI = pair_lst(bsnds:bends,1);
    SJ = pair_lst(bsnds:bends,3);
    all_vec_snds = [SI;SJ];
    int_snds = unique(all_vec_snds);
    
    % Part A2: Isolate all ending time steps of the repeats of length BW
    
    EI = pair_lst(bsnds:bends,2); % Similar to definition for SI
    EJ = pair_lst(bsnds:bends,4); % Similar to definition for SJ
    all_vec_ends = [EI;EJ];
    int_ends = unique(all_vec_ends);
    
    % Part B: Use the current diagonal information to search for diagonals 
    %         of length BW contained in larger diagonals and thus were not
    %         detected because they were contained in larger diagonals that
    %         were removed by our method of eliminating diagonals in
    %         descending order by size
    
    [add_srows] = find_add_srows_both_check_no_anno(pair_lst, int_snds, bw);
    [add_mrows] = find_add_mrows_both_check_no_anno(pair_lst, int_snds, bw);
    [add_erows] = find_add_erows_both_check_no_anno(pair_lst, int_ends, bw);

    % Add the new pairs of repeats to the temporary list ADD_MAT
    
    add_mat = [add_mat; add_srows; add_mrows; add_erows];

In [248]:
#Tells you essentially how many unique bandwidths there are thus how many times you need search for diagonals 
for j in range(1, bw_num + 1):
    
    #Set band_width: traverse through each bw found in the list of unique bandwidth 
    band_width = bw_found[j - 1] 
    # Isolate pairs of repeats that are length bandwidth in two steps 
    
    # Step 1: Isolate the indices of the starting pairs 
    starting = np.where(pair_list[:,4] == band_width) 
    bsnds = starting[0][0] 
    
    # Step 2: Isolate the indices of the ending pairs 
    ending = np.where(pair_list[:,4] > band_width)
    if np.size(ending) == 0:
        bends = p
    else: 
        bends = ending[0][0] - 1 
    
    # Part A1: Isolate all starting time steps of the repeats of length bandwidth
    start_I = pair_list[bsnds:bend, 0] # 0 = first column
    start_J = pair_list[bsnds:bend, 2] # 2 = second column
    all_vec_snds = np.concatenate((start_I, start_J))
    int_snds = np.unique(all_vec_snds)
    
    # Part A2: Isolate all ending time steps of the repeats of length bandwidth
    end_I = pair_list[bsnds:bend, 1] # Similar to definition for SI
    end_J = pair_list[bsnds:bend, 3] # Similar to definition for SJ
    all_vec_ends = np.concatenate((end_I,end_J))
    int_ends = np.unique(all_vec_ends)
    
    # Part B: Use the current diagonal information to search for diagonals 
    #       of length BW contained in larger diagonals and thus were not
    #       detected because they were contained in larger diagonals that
    #       were removed by our method of eliminating diagonals in
    #       descending order by size
    add_srows = find_add_srows(pair_list, int_snds, band_width)
    add_erows = find_add_mrows(pair_list, int_snds, band_width)
    add_mrows = find_add_erows(pair_list, int_ends, band_width)
    

In [250]:
print(pair_list)
print(int_snds)
print(band_width)

[[ 1 10 46 55 10]
 [31 40 46 55 10]]
[ 1 31 46]
10


In [1]:

    
        # Part B: Use the current diagonal information to search for diagonals 
        #       of length BW contained in larger diagonals and thus were not
        #       detected because they were contained in larger diagonals that
        #       were removed by our method of eliminating diagonals in
        #       descending order by size
        add_srows = find_add_srows(pair_list, int_snds, band_width)
        add_erows = find_add_mrows(pair_list, int_snds, band_width)
        add_mrows = find_add_erows(pair_list, int_ends, band_width)
        
        # Check if any of the arrays are empty, if so, reshape them
        ## these are lines I just removed
        ##if add_mrows == 0:
           ## column = add_srows.shape[1]
           ## add_mrows = np.array([],dtype=np.int64).reshape(0,column) 
        ##if add_srows == 0:
           ## column = add_erows.shape[1]
            ##add_mrows = np.array([],dtype=np.int64).reshape(0,column) 
        ##if add_erows == 0:
            ##column = add_srows.shape[1]
            ##add_mrows = np.array([],dtype=np.int64).reshape(0,column) 
       
        # Add the new pairs of repeats to the temporary list add_mat
        add_mat.extend((add_srows,add_erows,add_mrows))
        new_mat = np.column_stack(add_mat)
      
    # Step 2: Combine pair_list and new_mat. Make sure that you don't have any
    #         double rows in add_mat. Then find the new list of found 
    #         bandwidths in combine_mat.
    combo = [pair_list,new_mat]
    combine_mat = np.concatenate(combo)
    combine_mat = np.unique(combine_mat,axis=0)
    combine_inds = np.argsort(combine_mat[:,4]) # Return the indices that would sort combine_mat's fourth column
    combine_mat = combine_mat[combine_inds,:]
    c = np.size(combine_mat,axis=0)
    
    # Again, find the list of unique repeat lengths
    new_bw_found = np.unique(combine_mat[:,4])
    new_bw_num = np.size(new_bfound,axis=0)
    full_lst = []
    
    # Step 3: Loop over the new list of found bandwidths to add the annotation
    #         markers to each found pair of repeats
    for j in range(1,new_bw_num+1):
        new_bw = new_bw_found[j-1]
        # Isolate pairs of repeats in combine_mat that are length bandwidth
        new_bsnds = np.amin((combine_mat[:,4] == new_bw).nonzero()) # Return the minimum of the array
        new_bends = (combine_mat[:,4] > new_bw).nonzero() 
        # Convert new_bends into an array
        new_bend = np.array(new_bends)
    
        if new_bend.size > 0:
            new_bend = np.amin(new_bend)
        else:
            new_bend = c
        
        band_width_mat = np.array((combine_mat[new_bsnds:new_bend,]))
        length_band_width_mat = np.size(band_width_mat,axis=0)
        temp_anno_lst = np.concatenate((band_width_mat,(np.zeros((length_band_width_mat,1)))),axis=1).astype(int)
        # Part C: Get annotation markers for this bandwidth
        temp_anno_lst = add_annotations(temp_anno_lst, song_length)
        full_lst.append(temp_anno_lst)
        final_lst = np.vstack(full_lst)
    
    lst_out = final_lst
    
    return lst_out
 


What is bw_found? [10 15]
What is bw_num? 2

What is p? 4
What is band_width? 10
What is bsnds? (array([1, 2]),) <class 'numpy.int64'>
What is bsnds? 2
What is bends--non-array? (array([0, 3]),)
What is bends--array? [[0 3]]

entered the statement - bend.size > 0
np.amin(bend) 0

start_I []
start_J []
all_vec_snds? 
 []

all_vec_ends? 
 []
What is pair_list? 
 [[ 1 15 31 45 15]
 [ 1 10 46 55 10]
 [31 40 46 55 10]
 [10 20 40 50 15]]
What is int_snds? 
 []
What is int_ends? 
 []
What is bw? 
 10


NameError: name 'find_add_srows' is not defined